name: SoulEvents-AirDrop
version: '${version}'
main: bm.b0b0b0.soulevents.airdrop.AirDropPlugin
api-version: '1.21'
authors: [ b0b0b0 ]
depend: [ SoulEvents ]
softdepend: [ WorldGuard, Vault, SoulEvents-MobWaves ]

libraries:
  - net.elytrium:serializer:1.1.1
  - com.zaxxer:HikariCP:5.1.0
  - org.xerial:sqlite-jdbc:3.45.3.0

commands:
  airdrop:
    description: AirDrop event commands
    permission: soulevents.airdrop.staff
    aliases: [ ad ]

permissions:
  soulevents.airdrop.staff:
    description: AirDrop staff commands and admin GUI
    default: op
  soulevents.airdrop.summon:
    default: op
  soulevents.airdrop.bypass:
    description: Skip concurrent spawn limits for testing
    default: op
  soulevents.airdrop.open.donate:
    description: Open donate airdrop chests when permission requirement is enabled
    default: false
