name: SoulEvents
version: '${version}'
main: bm.b0b0b0.soulevents.core.SoulEventsPlugin
api-version: '1.21'
authors: [ b0b0b0 ]
load: STARTUP

softdepend:
  - FastAsyncWorldEdit
  - PlaceholderAPI

libraries:
  - net.elytrium:serializer:1.1.1
  - com.zaxxer:HikariCP:5.1.0
  - org.xerial:sqlite-jdbc:3.45.3.0

commands:
  soulevents:
    description: SoulEvents administration
    permission: soulevents.admin
    aliases: [ se, events ]

permissions:
  soulevents.admin:
    default: op
